# config/packages/security.yaml
security:
    # Configuration générale pour les password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Fournisseur d'utilisateurs pour charger les utilisateurs à partir de la base de données
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Configuration du firewall pour l'environnement de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Configuration du firewall principal pour l'application
        main:
            lazy: true
            provider: app_user_provider
            # Vous pouvez activer différentes méthodes d'authentification ici

    # Contrôle d'accès pour les différentes parties de votre application
    access_control:
        # Exemple : protéger une partie de l'administration
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Exemple : protéger le profil utilisateur
        - { path: ^/profile, roles: ROLE_USER }

    # Configuration spécifique à l'environnement de test
    # Permet de réduire le coût des hashages de mot de passe pour optimiser les tests
    # et réduire le temps d'exécution des tests
    when@test:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Coût le plus bas pour bcrypt
                time_cost: 3 # Coût le plus bas pour argon
                memory_cost: 10 # Coût le plus bas pour argon
